### ISSUE TITLE
Update Turbo ORM Sample to include newer components

### ISSUE THREAD

**Issue by amccook** [turbonomic/orm#14]
The following components are missing from the sample Turbo ORM located here: https://github.com/turbonomic/orm/blob/master/config/samples/turbo_operator_resource_mapping_sample_cr.yaml

- mediation-awscloudbilling
- mediation-flexera
- mediation-gcpbilling
- mediation-gcpproject
- mediation-gcpsa
- mediation-ibmstorage-flashsystem
- mediation-webhook

Please add so that end users don't see failed resize actions on these containers.
@evat-pm

**Comment by amccook** [comment]
Additional probes missing:

- mediation-jboss
- mediation-websphere
- mediation-weblogic
- mediation-tanium

**Comment by evat-pm** [comment]
Changes made directly to master https://github.com/turbonomic/orm/blob/master/config/samples/turbo_operator_resource_mapping_sample_cr.yaml
Issue closed as done.
