### ISSUE TITLE
crd is missing schema

### ISSUE THREAD

**Issue by mrulke** [turbonomic/orm#7]
The current crd is missing      https://raw.githubusercontent.com/turbonomic/orm/master/config/crd/bases/turbo_operator_resource_mapping_crd.yaml

```
schema:
        openAPIV3Schema:
```

is failing to deploy

**Comment by esara** [comment]
for k8s 1.22 and later, please use https://github.com/turbonomic/orm/blob/master/config/crd/bases/turbo_operator_resource_mapping_crd_v1.yaml

**Comment by esara** [comment]
closed by https://github.com/turbonomic/orm/pull/8
